### PR TITLE
Feature/render tag

### PR DESCRIPTION
**Pull request by markglenn**
Add render tag

See: https://shopify.github.io/liquid/tags/template/

### CODE REVIEW

**Comment by stevencorona** [comment]
Cool, looks similar to how I implemented it as well. 

I haven't read through / fully understood the changes from #37 yet, so it may answer this, but for example, for a render tag like:

```
{% render 'foobar'.html, bar: bar %}
```

We want to limit the context scope to just `bar`, but there's also some subset of global variables we want to keep (for example, using shopify as an example, `request`). The way I handle it right now is that I track a list of the global variables in the context and clone those into the child context automatically. Is it possible to have some notion of globals as part of this?

**Comment by markglenn** [comment]
Based on how I'm reading their documentation, you would not have access to global variables. The only variables you would have access to are those passed in at the render call.

However, I'm with you that Shopify itself is doing something different. The context object is quite complex and I don't fully understand it, but there are many scopes that can contain variables. There is [Context.environment](https://github.com/markglenn/liquex/blob/ca7bc61c9980b999a2e4fd5a068d3b2176043f25/lib/liquex/context.ex#L19) that is basically your starting variables that are defined when you create a context. There is also [Context.scope](https://github.com/markglenn/liquex/blob/ca7bc61c9980b999a2e4fd5a068d3b2176043f25/lib/liquex/context.ex#L20) which is used to track current variables defined within a "scope" such as a loop. Nesting loops creates nesting scopes as seen [here](https://github.com/markglenn/liquex/blob/ca7bc61c9980b999a2e4fd5a068d3b2176043f25/lib/liquex/scope.ex#L16). Lastly, there is a 3rd location specific to [cycles/iterators](https://github.com/markglenn/liquex/blob/ca7bc61c9980b999a2e4fd5a068d3b2176043f25/lib/liquex/context.ex#L12).

Now, Shopify's documentation says this:

https://shopify.github.io/liquid/tags/template/

> The code within the rendered template **does not automatically** have access to the variables assigned using [variable tags](https://shopify.github.io/liquid/tags/variable/) within the parent template. Similarly, variables assigned within the rendered template cannot be accessed by code in any other template.

... which is very vague. I bolded the vague part.

What I currently do is create a new context and copy over everything besides the multiple scopes. I feel like maybe the environment variables should be kept around.

To add more complexity, the scopes also have something that is defined as a "global" which just puts the variable at the top level scope. Understanding the many uses of the context and scopes is on my todo list.

I know this was a lot of information, but it's complicated. I need to dig deeper into the scoping rules again before I can fully release this.

**Comment by markglenn** [comment]
I've been deep in Shopify's Liquid code to figure out what they do here and it appears that there is yet another scope of variables called the `static_environment`. These variables are truly global and accessible within nested render calls.

I describe it [here](https://github.com/markglenn/liquex/blob/035f771c714f464ef2b1eecb2f62e6cf4a0ca838/lib/liquex/context.ex#L16). In your case, when you create the context, you should do something like the following:

    context = Liquex.Context.new(%{not_accessible_in: :nested_render_tags},
      static_environment: %{request: my_request_variable})

**Comment by stevencorona** [comment]
Cool - that solves my use case perfectly and will be a drop in replacement for my custom tag.

One last thing - we cache the liquid ast heavily at runtime (and actually run `Liquid.parse` at compile time via a macro for our "default" templates for the base case of templates that haven't been modified by the user). Would it be possible to have `read_template_file` return a string OR the AST & have the render tag skip parsing if it gets an AST?

**Comment by markglenn** [comment]
Caching is going to be built in to the render tag, outside of the FileSystem. The render call will cache the results after parsing in the next code push. There's actually plans on caching a whole lot more within the context object, such as memoizing some of the variables when I decide to tackle [drops](https://github.com/Shopify/liquid/wiki/Introduction-to-Drops).

Are you caching the AST between render calls? The plan was to cache the AST for the partials within the context, but that won't help you caching the partial across multiple render calls. Maybe there's something with reusing the context but clearing out variables between renders. I'm interested in any ideas you have.

Reading through the Liquid code again, they have a concept called [Registers](https://github.com/Shopify/liquid/blob/master/lib/liquid/registers.rb), and the registers have a `static` component that's shared across all the contexts created. This includes the partial cache. I could probably mimic this with a genserver or something similar. The static registers also include the configurations for file systems and the template factory.

I'd like to keep the FileSystem protocol pretty dumb here and not have parsing built into it.

**Comment by stevencorona** [comment]
Yeah, we cache the AST's between render calls in an ets table. In theory, each individual liquid template is only ever parsed once during the lifetime of the app unless it is modified by the end-user.

We do this for the main template (outside of Liquex/render tag), and before calling `Liquex.render`, we set a loader function on the context that the render_tag uses to load templates at runtime. The loader function returns the AST from the cache. This is similar to how you have the implemented the filesystem call, minus it returning an AST. Basic example below.

I've also debated the idea of scanning the AST after parsing and just expanding all of the render tags (essentially replacing the render tag w/ it's parsed AST) at parse-time. The downside is that you'd only be able to do this for templates that are included as string literals, but that's 99% of the case for us. The benefit for my use case would be that you can manipulate the whole tree, since we actually pre-process the AST before rendering to extract the static literals + capture the dynamic tags + assigns and transform it into a `%Phoenix.LiveView.Rendered{}` struct, which allows us to get LiveView diff-tracking on the liquid template - but since we can't see "inside" the render tag until runtime/render time, we're forced to do the transformation in the render tag at runtime.

Anyways, just food for thought, I know that liveview use-case is pretty atypical.

```
{:ok, ast} = get_template(name)
context = Liquex.Context.new(filter_module: FilterModule)
private = context.private |> Map.put(:loader, fn template_name, _ -> get_template(template_name) end)
context = %{context | private: private}

{result, _} = Liquex.render(ast, context)

def get_template(name) do
  case get_template_from_ast_cache(directory) do
    {:ast, ast} -> {:ok, ast}
    {:template, template} -> Liquid.parse(template)
  end
end

# render_tag.ex

def render(template_name, context) do
  ast = context.private.loader.(template_name)
  # ... bunch of stuff to build child context
  Liquex.render(ast, context)
end
```

**Comment by markglenn** [comment]
I've added a behavior for caching and two basic caching modules.

My original take at this was that I would add a behavior so you could plug in something like Cachex because I don't want to try to make a full featured caching mechanism, however I felt like it should have _something_ out of the box. By default, caching is disabled.

To use the ETS based cache, you would add it to your context:

    :ok = Liquex.Cache.SimpleCache.init()
    Context.new(%{...}, cache: Liquex.Cache.SimpleCache)

Right now, caching is limited to only render partials, but I plan to expand on that.

Since you have your own caching mechanism, let me know if the behavior I defined is enough to plug yours in. Check out the SimpleCache module for how to use it.

**Pull request merged**
